---
include:
  - board: nice_nano
    shield: cradio_left
  - board: nice_nano
    shield: cradio_right
  - board: nice_nano
    shield: settings_reset
  - board: nice_nano_v2
    shield: tester_pro_micro
