manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # Define any additional modules you want to include in your build
    - name: zmk-config
      remote: zmkfirmware
      revision: main
      path: config # This would point to your custom configuration directory

  self:
    path: config
